### ISSUE TITLE
Adding a list of listings

### ISSUE THREAD

**Issue by manujinda** [publicus/unofficial-uoregon-grad-school-dissertation-latex-markdown-apa-format#5]
I am using the listings package to have program listings in my thesis. Listings work fine. I am trying to add a list of listings (just like list of figures). The listings package manual says use \lstlistoflistings to generate the list of listings.

I managed to get a listing but it has two issues:

1. It makes the list of listings the 1st page of the thesis. Should move this to the roman numbered pages.
2. The list of listing does not have the "Listing               Page" heading.

I was successful in introducing a List of Algorithms with no problems.

Could you please let me know how to fix my list of listings?

Thanks.

**Comment by jglev** [comment]
Hello,

I'm sorry that I've waited this long to respond. Thank you for filing an enhancement request here!

This repository is primarily for tracking changes that people have made and submitted back to the repo.; I'm not able to do development work for specific cases. Thus, if you've figured this out, or speak with another grad. student who figures it out, please do submit the changes here!

If anyone else sees this issue, this ticket is also a good space to discuss and collaborate on solutions for this request.

My very best,
Jacob

**Comment by sampollard** [comment]
List of listings is actually now supported. You simply need to use the option `listings` when using the documentclass. For those interested, the fix consisted of adding an additional temp file ending in `.lol` and then adding it to the table of contents, around

https://github.com/unofficial-uoregon-dissertation-formats/unofficial-uoregon-grad-school-dissertation-latex-markdown-apa-format/blob/9efc5fc21bfd3e26e331d1b4ba37d9edf4100200/latex_files/uothesis.cls#L784

and

https://github.com/unofficial-uoregon-dissertation-formats/unofficial-uoregon-grad-school-dissertation-latex-markdown-apa-format/blob/9efc5fc21bfd3e26e331d1b4ba37d9edf4100200/latex_files/uothesis.cls#L665
