### ISSUE TITLE
Page Numbers Missing

### ISSUE THREAD

**Issue by benmbrennan** [publicus/unofficial-uoregon-grad-school-dissertation-latex-markdown-apa-format#7]
I'm working with this and I've made minimal changes but for some reason my page numbers aren't printing at all.  Is there anything in the Class file that might be causing this?

**Comment by jglev** [comment]
Thank you for your message! I'm not aware of what in the class file, or the header options, would cause this, and don't remember running into anything similar while working on my own dissertation. Nothing popped out at me when I re-read those files just now, either, unfortunately.

@jflournoy, would you be willing to look over this, as well?

In any case, @benmbrennan , I'll leave this issue open -- when you do find an answer, please consider posting back here!

**Comment by benmbrennan** [comment]
This turned out to be the fault of a package I’d added.  Sorry about this.  False alarm.
