### ISSUE TITLE
Unable to import gensymb, conflicts with \degree definition in uothesisapa.cls?

### ISSUE THREAD

**Issue by tzcrawford** [publicus/unofficial-uoregon-grad-school-dissertation-latex-markdown-apa-format#8]
I don't understand exactly what all is done exactly in `uothesisapa.cls` where general formatting is declared, but I believe `\degree` is manually defined here. If you add `\usepackage{gensymb}` elsewhere in the document (e.g. `0_uothesisapa_preamble.tex`),` pdflatex `gives an error that `\degree` is already defined. In `gensymb`, this function would print the degree symbol (°).

I found a workaround in instead importing the `textcomp` package and using `\textdegree` function instead.

**Comment by sampollard** [comment]
This is an unfortunate annoyance. Another, more invasive fix would be to redefine uothesis as having `uodegree` instead of `degree`. I'm going to close this since you found a workaround.
